- hosts: localhost
  roles:
    - role: standard-test-beakerlib
      tags:
        - classic
        - container
      tests:
        - basic
        - hostnamectl
        - tmpfiles
        - killmode
        - localectl
        - loginctl
        - timedatectl
        - rlimits
        - journal
        - jobs
        - dropin
        - sched
        - path
        - issue-1981
        - issue-2467
        - issue-3166
