- hosts: localhost
  roles:
    - role: standard-test-beakerlib
      tags:
        - classic
        - container
      tests:
        - basic
        - hostnamectl
        - tmpfiles
        - killmode
        - localectl
        - loginctl
        - timedatectl
        - rlimits
        - journal
        - jobs
        - dropin
        - sched
        - path
        - execute
        - socket
        - link
        - issue-1981
        - issue-2467
        - issue-3166
        - network
    required_packages:
        - ethtool                   # link tests needs this package
        - findutils                 # beakerlib needs find command
        - kernel-modules-extra      # network test needs vcan module
        - lsof                      # socket test needs this package
        - systemd
